# Generated by Django 3.1.7 on 2021-03-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
    ]
